# Generated by Django 3.1.6 on 2021-03-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='User_Name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='User_Contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
